export const sel = {
  userName: '[data-test="user.name"]',
  userNameError: '[data-test="user.name-error"]',
  userEmail: '[data-test="user.email"]',
  userEmailError: '[data-test="user.email-error"]',
  userHasEmail: '[data-test="user.hasEmail"]',
  userPassword: '[data-test="user.password"]',
  userPasswordError: '[data-test="user.password-error"]',
  userPasswordOutside: '[data-test="user.password-outside"]',

  one: '[data-test="one"]',
  two: '[data-test="two"]',
  three: '[data-test="three"]',

  submit: '[data-test="submit"]',
  reset: '[data-test="reset"]',
  config: '[data-test="config"]',
  sendData: '[data-test="send-form-data"]',
  action: '[data-test="action"]',

  isTouched: '[data-test="touched-result"]',
  touches: '[data-test="touches-result"]',
  isDirty: '[data-test="dirty-result"]',
  dirties: '[data-test="dirties-result"]',
  error: '[data-test="error-result"]',
  errors: '[data-test="errors-result"]',
  active: '[data-test="active-result"]',
  activeValues: '[data-test="activeValues-result"]',
  values: '[data-test="values-result"]',
};
